In [2]:
#Librerias para ciencia de datos 
import pandas as pd
import numpy as np

In [3]:
df1=pd.read_csv("CasosTotalesCumulativo.csv")
df1

,Region,2020-03-03,2020-03-04,2020-03-05,2020-03-06,2020-03-07,2020-03-08,2020-03-09,2020-03-10,2020-03-11,...,2021-12-17,2021-12-18,2021-12-19,2021-12-20,2021-12-21,2021-12-22,2021-12-23,2021-12-24,2021-12-25,2021-12-26
0,Arica y Parinacota,0,0,0,0,0,0,0,0,0,...,28756,28770,28805,28876,28942,28963,28994,29062,29120,29062
1,Tarapacá,0,0,0,0,0,0,0,0,0,...,44540,44568,44601,44620,44641,44660,44686,44709,44742,44765
2,Antofagasta,0,0,0,0,0,0,0,0,0,...,66277,66328,66391,66440,66482,66515,66576,66603,66670,66714
3,Atacama,0,0,0,0,0,0,0,0,0,...,30384,30417,30450,30489,30514,30534,30595,30635,30679,30702
4,Coquimbo,0,0,0,0,0,0,0,0,0,...,54239,54301,54340,54380,54423,54447,54478,54528,54583,54641
5,Valparaíso,0,0,0,0,0,0,0,0,0,...,136437,136589,136744,136832,136924,137023,137178,137324,137482,137614
6,Metropolitana,0,1,2,3,4,6,9,10,14,...,748422,748752,748983,749222,749424,749714,750129,750489,750878,751245
7,O’Higgins,0,0,0,0,0,0,0,0,0,...,72849,72883,72905,72934,72959,72965,72985,73025,73076,73085
8,Maule,1,2,2,2,2,3,4,5,7,...,109030,109098,109169,109240,109289,109333,109376,109429,109476,109536
9,Ñuble,0,0,0,0,0,0,0,0,0,...,39060,39099,39135,39178,39203,39225,39272,39309,39340,39377
10,Biobío,0,0,0,0,0,0,1,1,1,...,165241,165435,165669,165846,165946,166074,166298,166529,166732,166902
11,Araucanía,0,0,0,0,0,0,0,0,0,...,103014,103124,103198,103267,103326,103396,103464,103536,103636,103728
12,Los Ríos,0,0,0,0,0,0,0,0,0,...,52926,52978,53039,53098,53145,53205,53315,53391,53470,53546
13,Los Lagos,0,0,0,0,1,1,1,1,1,...,97808,98019,98154,98260,98338,98430,98594,98725,98871,98967
14,Aysén,0,0,0,0,0,0,0,0,0,...,10158,10173,10183,10195,10200,10219,10223,10238,10255,10264
15,Magallanes,0,0,0,0,0,0,0,0,0,...,29922,29944,29964,29979,29984,30001,30023,30052,30069,30086
16,Total,1,3,4,5,7,10,15,17,23,...,1789109,1790524,1791776,1792902,1793786,1794750,1796232,1797631,1799125,1800280

In [4]:
df2=pd.read_csv("TotalesPorRegion.csv")
df2

,Region,Categoria,2020-03-03,2020-03-04,2020-03-05,2020-03-06,2020-03-07,2020-03-08,2020-03-09,2020-03-10,...,2021-12-17,2021-12-18,2021-12-19,2021-12-20,2021-12-21,2021-12-22,2021-12-23,2021-12-24,2021-12-25,2021-12-26
0,Arica y Parinacota,Casos acumulados,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,28756,28770,28805,28876,28942,28963,28994,29062,29120,29062
1,Tarapacá,Casos acumulados,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,44540,44568,44601,44620,44641,44660,44686,44709,44742,44765
2,Antofagasta,Casos acumulados,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,66277,66328,66391,66440,66482,66515,66576,66603,66670,66714
3,Atacama,Casos acumulados,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,30384,30417,30450,30489,30514,30534,30595,30635,30679,30702
4,Coquimbo,Casos acumulados,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,54239,54301,54340,54380,54423,54447,54478,54528,54583,54641
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
216,Los Ríos,Casos con sospecha de reinfeccion,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,68,69,69,70,70,71,71,71,71,71
217,Los Lagos,Casos con sospecha de reinfeccion,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,103,104,105,106,106,107,107,108,108,108
218,Aysén,Casos con sospecha de reinfeccion,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,18,18,18,18,18,18,18,18,18,19
219,Magallanes,Casos con sospecha de reinfeccion,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,176,176,177,177,177,177,177,177,177,177
220,Total,Casos con sospecha de reinfeccion,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2170,2176,2180,2187,2190,2192,2200,2204,2208,2214

In [5]:
df3=pd.read_csv("vacunacion.csv")
df3

,Region,Dosis,2020-12-24,2020-12-25,2020-12-26,2020-12-27,2020-12-28,2020-12-29,2020-12-30,2020-12-31,...,2021-12-13,2021-12-14,2021-12-15,2021-12-16,2021-12-17,2021-12-18,2021-12-19,2021-12-20,2021-12-21,2021-12-22
0,Total,Primera,420.0,5202.0,8345.0,8654.0,8654.0,8654.0,8654.0,8654.0,...,16476862.0,16507478.0,16534641.0,16559647.0,16581081.0,16583888.0,16584116.0,16604297.0,16622141.0,16631375.0
1,Total,Segunda,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,15768678.0,15789568.0,15808670.0,15825344.0,15839825.0,15841622.0,15841768.0,15856751.0,15871010.0,15879060.0
2,Total,Unica,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,573409.0,573457.0,573516.0,573546.0,573564.0,573567.0,573570.0,573591.0,573604.0,573611.0
3,Total,Refuerzo,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,9576553.0,9686101.0,9785214.0,9873979.0,9953572.0,9970323.0,9972483.0,10063769.0,10150434.0,10200189.0
4,Aysén,Primera,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,88930.0,89074.0,89197.0,89307.0,89448.0,89481.0,89489.0,89573.0,89658.0,89694.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63,Maule,Refuerzo,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,591377.0,597212.0,602415.0,607151.0,611754.0,612114.0,612462.0,617514.0,622256.0,624568.0
64,Metropolitana,Primera,420.0,2938.0,5425.0,5719.0,5719.0,5719.0,5719.0,5719.0,...,6506506.0,6518936.0,6530067.0,6540592.0,6549395.0,6550792.0,6550807.0,6558639.0,6565415.0,6569112.0
65,Metropolitana,Segunda,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,6224113.0,6231680.0,6238831.0,6244991.0,6250167.0,6250993.0,6251007.0,6256257.0,6261255.0,6264285.0
66,Metropolitana,Unica,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,225461.0,225491.0,225528.0,225528.0,225528.0,225528.0,225528.0,225536.0,225536.0,225537.0
67,Metropolitana,Refuerzo,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3929786.0,3971625.0,4009049.0,4043233.0,4073143.0,4081361.0,4081491.0,4115633.0,4147858.0,4167514.0